# Generated by Django 3.2.2 on 2021-06-06 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencie',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Culminación'),
        ),
        migrations.AddField(
            model_name='experiencie',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio'),
        ),
    ]
