# Generated by Django 3.2.2 on 2021-06-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210606_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experiencie',
        ),
    ]
