# Generated by Django 3.2.2 on 2021-06-06 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_delete_experiencie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio')),
                ('end', models.DateField(default=datetime.date.today, verbose_name='Fecha de Culminación')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de la experiencia')),
                ('institute', models.CharField(max_length=100, verbose_name='Institución')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('category', models.ManyToManyField(related_name='get_post', to='about.Category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencias',
                'ordering': ['-created'],
            },
        ),
    ]
