# Generated by Django 3.2.2 on 2021-06-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_experiencie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiencie',
            new_name='ExperiencieA',
        ),
        migrations.AlterModelOptions(
            name='experienciea',
            options={'ordering': ['-created'], 'verbose_name': 'Experiencia Academica', 'verbose_name_plural': 'Experiencias Academicas'},
        ),
    ]
