# Generated by Django 3.2.2 on 2021-06-06 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20210606_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='about', verbose_name='Imagen de Perfil')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Experiencia Academica',
                'verbose_name_plural': 'Experiencias Academicas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ExperiencieL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Fecha de Inicio')),
                ('end', models.DateField(default=datetime.date.today, verbose_name='Fecha de Culminación')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo de la experiencia')),
                ('institute', models.CharField(max_length=100, verbose_name='Institución')),
                ('city', models.TextField(verbose_name='Descripcion del cargo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='experienciea',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
