# Generated by Django 3.2.2 on 2021-06-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20210606_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experienciel',
            old_name='city',
            new_name='description',
        ),
    ]
