# Generated by Django 3.2.2 on 2021-06-17 18:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_rename_city_experienciel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='aptitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('aptitudes', 'Aptitudes - Habilidades personales'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Aptitud',
                'verbose_name_plural': 'Aptitudes',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='intereses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('aptitudes', 'Aptitudes - Habilidades personales'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Interes / Hobbie',
                'verbose_name_plural': 'Intereses / Hobbies',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='skills_idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('aptitudes', 'Aptitudes - Habilidades personales'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('knowledge_level', models.CharField(max_length=100, verbose_name='Nivel de conocimiento')),
            ],
            options={
                'verbose_name': 'Habilitad Tecnica / Idioma',
                'verbose_name_plural': 'Habilidades Tecnicas / Idiomas',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='experienciel',
            name='institute',
        ),
        migrations.AddField(
            model_name='experienciea',
            name='category',
            field=models.CharField(choices=[('EA', 'Experiencia Academica'), ('EL', 'Experiencia Laboral')], default=('EA', 'Experiencia Academica'), max_length=20, verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='experienciel',
            name='category',
            field=models.CharField(choices=[('EA', 'Experiencia Academica'), ('EL', 'Experiencia Laboral')], default=('EA', 'Experiencia Academica'), max_length=20, verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='experienciel',
            name='employeer',
            field=models.CharField(default='', max_length=100, verbose_name='Ente empleador'),
        ),
        migrations.AlterField(
            model_name='experienciel',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion del cargo'),
        ),
    ]
