# Generated by Django 3.2.2 on 2021-06-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20210617_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciea',
            name='category',
        ),
        migrations.RemoveField(
            model_name='experienciel',
            name='category',
        ),
    ]
