# Generated by Django 3.2.2 on 2021-06-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20210617_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_idiomas',
            name='knowledge_level',
            field=models.CharField(choices=[('basico', 'Basico (competente)'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default=('basico', 'Basico (competente)'), max_length=100, verbose_name='Nivel de conocimiento'),
        ),
    ]
