# Generated by Django 3.2.2 on 2021-06-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_alter_skills_idiomas_knowledge_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aptitudes',
            new_name='intereses_aptitudes',
        ),
        migrations.DeleteModel(
            name='intereses',
        ),
        migrations.AlterModelOptions(
            name='intereses_aptitudes',
            options={'ordering': ['-created'], 'verbose_name': 'Intereses & Aptitudes'},
        ),
        migrations.AlterModelOptions(
            name='skills_idiomas',
            options={'ordering': ['-created'], 'verbose_name': 'Habilitad Tecnica & Idioma'},
        ),
    ]
