# Generated by Django 3.2.2 on 2021-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20210617_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='intereses_aptitudes',
            name='_subcategory',
            field=models.CharField(choices=[('i_h', (('in', 'Interes'), ('hb', 'Hobbie'))), ('ap_', 'Aptitud')], default=('i_h', (('in', 'Interes'), ('hb', 'Hobbie'))), max_length=3, verbose_name='Sub categoria'),
        ),
    ]
