# Generated by Django 3.2.2 on 2021-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_intereses_aptitudes__subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_idiomas',
            name='knowledge_level',
            field=models.IntegerField(choices=[(1, 'Basico (competente)'), (2, 'Intermedio'), (3, 'Avanzado')], default=(1, 'Basico (competente)'), verbose_name='Nivel de conocimiento'),
        ),
    ]
