# Generated by Django 3.2.2 on 2021-06-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_alter_skills_idiomas_knowledge_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intereses_aptitudes',
            name='_subcategory',
            field=models.CharField(choices=[('-', (('in', 'Interes'), ('hb', 'Hobbie'))), ('ap', 'Aptitud')], default=('-', (('in', 'Interes'), ('hb', 'Hobbie'))), max_length=2, verbose_name='Sub categoria'),
        ),
    ]
