# Generated by Django 3.2.2 on 2021-08-01 16:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20210728_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='intereses_hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('aptitudes', 'Aptitudes - Habilidades personales'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('subcategory', models.CharField(choices=[('in', 'Intereses'), ('hb', 'Hobbies')], default=('in', 'Intereses'), max_length=2, verbose_name='Sub categoria')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Intereses & Aptitudes',
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='intereses_aptitudes',
        ),
    ]
