# Generated by Django 3.2.2 on 2021-08-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20210801_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intereses_hobbies',
            options={'ordering': ['-created'], 'verbose_name': 'Hobbies '},
        ),
    ]
