# Generated by Django 3.2.2 on 2021-08-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_alter_intereses_hobbies_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intereses_hobbies',
            options={'ordering': ['-created'], 'verbose_name': 'Intereses & Hobbies'},
        ),
        migrations.AlterField(
            model_name='intereses_hobbies',
            name='category',
            field=models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='skills_idiomas',
            name='category',
            field=models.CharField(choices=[('skills', (('lenguajes', 'Lenguajes de Programacion'), ('frameworks', 'Frameworks - Marcos de Trabajo'), ('db', 'Bases de datos - Data bases'))), ('idiomas', 'Idiomas - Lenguajes'), ('intereses', 'Intereses - Hobbies')], max_length=20, verbose_name='Categorias'),
        ),
    ]
