# Generated by Django 3.2.2 on 2021-08-01 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_auto_20210801_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='intereses_hobbies_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='about')),
                ('default', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('i_h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.intereses_hobbies', verbose_name='Hobbies e Intereses')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-created'],
            },
        ),
    ]
