# Generated by Django 3.2.2 on 2021-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210523_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(default='', verbose_name='Descripción detallada'),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='', max_length=140, verbose_name='Descripción corta'),
        ),
    ]
